/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import archivo.Archivo;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import modelo.Alcancia;
import static vista.main.app;

/**
 *
 * @author branz
 */
public class Vista extends javax.swing.JFrame {
File archivo;
Alcancia alc;
    /**
     * Creates new form Vista
     */
   // public static Alcancia alc = new Alcancia();
  
    public Vista() {
        initComponents();
        setLocationRelativeTo(null);        // Centering on screen...
        setSize(660, 680);                  // Setting dimensions...
        setTitle("AlCancia Zabud");  // A simple greeting...
          alc = Archivo.leer(app);

            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoMonedas = new javax.swing.ButtonGroup();
        all = new javax.swing.JPanel();
        headimg = new javax.swing.JLabel();
        panelMonedas = new javax.swing.JPanel();
        moneda50 = new javax.swing.JRadioButton();
        moneda100 = new javax.swing.JRadioButton();
        moneda200 = new javax.swing.JRadioButton();
        moneda500 = new javax.swing.JRadioButton();
        moneda1000 = new javax.swing.JRadioButton();
        bttAddMoneda = new javax.swing.JButton();
        cant50 = new javax.swing.JLabel();
        cant100 = new javax.swing.JLabel();
        cant200 = new javax.swing.JLabel();
        cant500 = new javax.swing.JLabel();
        cant1000 = new javax.swing.JLabel();
        panelResultados = new javax.swing.JPanel();
        txtResultado = new javax.swing.JTextField();
        btTotalDinero = new javax.swing.JButton();
        btTotalMonedas = new javax.swing.JButton();
        btTotalD50 = new javax.swing.JButton();
        btTotalD100 = new javax.swing.JButton();
        btTotalD200 = new javax.swing.JButton();
        btTotalD500 = new javax.swing.JButton();
        btTotalD1000 = new javax.swing.JButton();
        btVaciarAlcancia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 630));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        all.setMinimumSize(new java.awt.Dimension(650, 650));
        all.setPreferredSize(new java.awt.Dimension(650, 650));
        all.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headimg.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        headimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headimg.setText("ALCANCIA ZABUD");
        headimg.setToolTipText("");
        headimg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        headimg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        headimg.setEnabled(false);
        all.add(headimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 160));

        panelMonedas.setBorder(javax.swing.BorderFactory.createTitledBorder("Monedas"));
        panelMonedas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grupoMonedas.add(moneda50);
        moneda50.setText("50$");
        panelMonedas.add(moneda50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        grupoMonedas.add(moneda100);
        moneda100.setText("100$");
        panelMonedas.add(moneda100, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        grupoMonedas.add(moneda200);
        moneda200.setText("200$");
        panelMonedas.add(moneda200, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        grupoMonedas.add(moneda500);
        moneda500.setText("500$");
        panelMonedas.add(moneda500, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        grupoMonedas.add(moneda1000);
        moneda1000.setText("1000$");
        panelMonedas.add(moneda1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        bttAddMoneda.setText("Agregar Moneda");
        bttAddMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddMonedaActionPerformed(evt);
            }
        });
        panelMonedas.add(bttAddMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        cant50.setText("0");
        cant50.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant50.setEnabled(false);
        panelMonedas.add(cant50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        cant100.setText("0");
        cant100.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant100.setEnabled(false);
        panelMonedas.add(cant100, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        cant200.setText("0");
        cant200.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant200.setEnabled(false);
        panelMonedas.add(cant200, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        cant500.setText("0");
        cant500.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant500.setEnabled(false);
        panelMonedas.add(cant500, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        cant1000.setText("0");
        cant1000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant1000.setEnabled(false);
        panelMonedas.add(cant1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        all.add(panelMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 630, 170));

        panelResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        panelResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        panelResultados.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 190, 70));

        btTotalDinero.setText("Total Dinero");
        btTotalDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalDineroActionPerformed(evt);
            }
        });
        panelResultados.add(btTotalDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        btTotalMonedas.setText("Total Monedas");
        btTotalMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalMonedasActionPerformed(evt);
            }
        });
        panelResultados.add(btTotalMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        btTotalD50.setText("Total Dinero 50$");
        btTotalD50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalD50ActionPerformed(evt);
            }
        });
        panelResultados.add(btTotalD50, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btTotalD100.setText("Total Dinero 100$");
        btTotalD100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalD100ActionPerformed(evt);
            }
        });
        panelResultados.add(btTotalD100, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        btTotalD200.setText("Total Dinero 200$");
        btTotalD200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalD200ActionPerformed(evt);
            }
        });
        panelResultados.add(btTotalD200, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        btTotalD500.setText("Total Dinero 500$");
        btTotalD500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalD500ActionPerformed(evt);
            }
        });
        panelResultados.add(btTotalD500, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        btTotalD1000.setText("Total Dinero 1000$");
        btTotalD1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalD1000ActionPerformed(evt);
            }
        });
        panelResultados.add(btTotalD1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        btVaciarAlcancia.setText("Vaciar Alcancia");
        btVaciarAlcancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVaciarAlcanciaActionPerformed(evt);
            }
        });
        panelResultados.add(btVaciarAlcancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        all.add(panelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 630, 280));

        getContentPane().add(all, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btTotalD500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalD500ActionPerformed
        txtResultado.setText(String.valueOf(alc.cantdinero500() + "$"));
    }//GEN-LAST:event_btTotalD500ActionPerformed

    private void bttAddMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddMonedaActionPerformed
        if (moneda50.isSelected()) {
            
            alc.addncoin50();
            cant50.setText(String.valueOf(alc.getNcoin50()));
        } else if (moneda100.isSelected()) {
            alc.addncoin100();
            cant100.setText(String.valueOf(alc.getNcoin100()));
        } else if (moneda200.isSelected()) {
            alc.addncoin200();
            cant200.setText(String.valueOf(alc.getNcoin200()));
        } else if (moneda500.isSelected()) {
            alc.addncoin500();
            cant500.setText(String.valueOf(alc.getNcoin500()));
        } else if (moneda1000.isSelected()) {
            alc.addncoin1000();
            cant1000.setText(String.valueOf(alc.getNcoin1000()));
        } else {
            alc.doNothing();
        }
        
        Archivo.escribir(alc);
    }//GEN-LAST:event_bttAddMonedaActionPerformed

    private void btTotalDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalDineroActionPerformed
        txtResultado.setText(String.valueOf(alc.cantdinero() + "$"));
    }//GEN-LAST:event_btTotalDineroActionPerformed

    private void btTotalMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalMonedasActionPerformed
        txtResultado.setText(String.valueOf(alc.cantcoin() + " Monedas"));
    }//GEN-LAST:event_btTotalMonedasActionPerformed

    private void btTotalD50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalD50ActionPerformed
        txtResultado.setText(String.valueOf(alc.cantdinero50() + "$"));
    }//GEN-LAST:event_btTotalD50ActionPerformed

    private void btTotalD100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalD100ActionPerformed
        txtResultado.setText(String.valueOf(alc.cantdinero100() + "$"));
    }//GEN-LAST:event_btTotalD100ActionPerformed

    private void btTotalD200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalD200ActionPerformed
        txtResultado.setText(String.valueOf(alc.cantdinero200() + "$"));
    }//GEN-LAST:event_btTotalD200ActionPerformed

    private void btTotalD1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalD1000ActionPerformed
        txtResultado.setText(String.valueOf(alc.cantdinero1000() + "$"));
    }//GEN-LAST:event_btTotalD1000ActionPerformed

    private void btVaciarAlcanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVaciarAlcanciaActionPerformed
        alc.setNcoin50(0);
        cant50.setText(String.valueOf(alc.getNcoin50()));
        alc.setNcoin100(0);
        cant100.setText(String.valueOf(alc.getNcoin100()));
        alc.setNcoin200(0);
        cant200.setText(String.valueOf(alc.getNcoin200()));
        alc.setNcoin500(0);
        cant500.setText(String.valueOf(alc.getNcoin500()));
        alc.setNcoin1000(0);
        cant1000.setText(String.valueOf(alc.getNcoin1000()));
        txtResultado.setText("");
    }//GEN-LAST:event_btVaciarAlcanciaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cant50.setText(String.valueOf(alc.getNcoin50()));
        cant100.setText(String.valueOf(alc.getNcoin100()));
        cant200.setText(String.valueOf(alc.getNcoin200()));
        cant500.setText(String.valueOf(alc.getNcoin500()));
        cant1000.setText(String.valueOf(alc.getNcoin1000()));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Vista().setVisible(true);

            }
        });
       

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel all;
    private javax.swing.JButton btTotalD100;
    private javax.swing.JButton btTotalD1000;
    private javax.swing.JButton btTotalD200;
    private javax.swing.JButton btTotalD50;
    private javax.swing.JButton btTotalD500;
    private javax.swing.JButton btTotalDinero;
    private javax.swing.JButton btTotalMonedas;
    private javax.swing.JButton btVaciarAlcancia;
    private javax.swing.JButton bttAddMoneda;
    private javax.swing.JLabel cant100;
    private javax.swing.JLabel cant1000;
    private javax.swing.JLabel cant200;
    private javax.swing.JLabel cant50;
    private javax.swing.JLabel cant500;
    private javax.swing.ButtonGroup grupoMonedas;
    private javax.swing.JLabel headimg;
    private javax.swing.JRadioButton moneda100;
    private javax.swing.JRadioButton moneda1000;
    private javax.swing.JRadioButton moneda200;
    private javax.swing.JRadioButton moneda50;
    private javax.swing.JRadioButton moneda500;
    private javax.swing.JPanel panelMonedas;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
